# Generated by Django 6.0.3 on 2026-03-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCityApis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingrecord',
            name='plate_number',
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('occupied', 'Occupied')], default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('businessuser', 'Business User'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'businessuser'}, on_delete=django.db.models.deletion.CASCADE, to='smartCityApis.user')),
            ],
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='parking_lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='smartCityApis.parkinglot'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default='cash', max_length=50)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartCityApis.parkingrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(default='car', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='smartCityApis.user')),
            ],
        ),
        migrations.AddField(
            model_name='parkingrecord',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartCityApis.vehicle'),
        ),
    ]
