# Generated by Django 6.0.3 on 2026-04-08 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCityApis', '0004_alter_parkinglot_options_alter_parkingrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='qr_code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='parkingstaff',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='parking_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('businessuser', 'Business User'), ('admin', 'Admin'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='MonthlyPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartCityApis.parkinglot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartCityApis.vehicle')),
            ],
        ),
    ]
